# Copied verbatim from stable-worldmodel @ 463ab63517b043ca6c3753b01e34ea6f145497c6
# Source: https://github.com/galilai-group/stable-worldmodel/blob/463ab63517b043ca6c3753b01e34ea6f145497c6/scripts/plan/config/launcher/local.yaml
# License: MIT (see example/wm_benchmark/ATTRIBUTION.md)
# @package _global_
# Local launcher configuration (no SLURM)

defaults:
  - override /hydra/launcher: basic

cache_dir: null # use stable-worldmodel default cache
